name: Release

on:
  push:
    tags:
      - '*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
    outputs:
      TAG: ${{ steps.get_tag.outputs.TAG }}
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    needs: prepare
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup and run pnpm install
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - run: cd src-tauri && cargo install cargo-bump --locked && cargo bump ${{ needs.prepare.outputs.TAG }}
      - name: ubuntu-20.04
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          mkdir -p src-tauri/ffmpeg
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          tar -xf ffmpeg-master-latest-linux64-gpl.tar.xz
          mv ffmpeg-master-latest-linux64-gpl/bin/ffmpeg src-tauri/ffmpeg/ffmpeg-x86_64-unknown-linux-gnu
      - name: windows-latest
        if: matrix.platform == 'windows-latest'
        run: |
          mkdir -p src-tauri/ffmpeg
          Invoke-WebRequest -Uri https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip -OutFile "ffmpeg-master-latest-win64-gpl.zip"
          unzip ffmpeg-master-latest-win64-gpl.zip
          mv ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe src-tauri/ffmpeg/ffmpeg-x86_64-pc-windows-msvc.exe
      - name: macos-latest
        if: matrix.platform == 'macos-latest'
        run: |
          mkdir -p src-tauri/ffmpeg
          wget https://www.osxexperts.net/ffmpeg7intel.zip
          unzip ffmpeg7intel.zip
          mv ffmpeg src-tauri/ffmpeg/ffmpeg-x86_64-apple-darwin
      - run: chmod +x src-tauri/ffmpeg/*
      - name: Build and upload a GitHub release
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: __VERSION__
          releaseName: 'XTuber __VERSION__'
          releaseBody: |
            New features and bug fixes.
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
