name: test

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
    outputs:
      TAG: ${{ steps.get_tag.outputs.TAG }}
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    needs: prepare
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup and run pnpm install
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - run: cd src-tauri && cargo install cargo-bump --locked && cargo bump ${{ needs.prepare.outputs.TAG }}
      - name: linux64
        run: |
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          mkdir -p src-tauri/ffmpeg
          tar -xf ffmpeg-master-latest-linux64-gpl.tar.xz -C src-tauri/ffmpeg --strip-components=1 bin/ffmpeg
          mv src-tauri/ffmpeg/ffmpeg src-tauri/ffmpeg/ffmpeg-x86_64-unknown-linux-gnu
      - name: linuxarm64
        run: |
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linuxarm64-gpl.tar.xz
          tar -xf ffmpeg-master-latest-linuxarm64-gpl.tar.xz -C src-tauri/ffmpeg --strip-components=1 bin/ffmpeg
          mv src-tauri/ffmpeg/ffmpeg src-tauri/ffmpeg/ffmpeg-arm-unknown-linux-gnu
      - name: win64
        run: |
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
          tar -xf ffmpeg-master-latest-win64-gpl.zip -C src-tauri/ffmpeg --strip-components=1 bin/ffmpeg.exe
          mv src-tauri/ffmpeg/ffmpeg.exe src-tauri/ffmpeg/ffmpeg-x86_64-windows-mvsc.exe
      - name: winarm64
        run: |
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-winarm64-gpl.zip
          tar -xf ffmpeg-master-latest-winarm64-gpl.zip -C src-tauri/ffmpeg --strip-components=1 bin/ffmpeg.exe
          mv src-tauri/ffmpeg/ffmpeg.exe src-tauri/ffmpeg/ffmpeg-x86_64-windows-mvsc.exe
      - name: mac64
        run: |
          wget https://www.osxexperts.net/ffmpeg7intel.zip
          tar -xf ffmpeg7intel.zip -C src-tauri/ffmpeg --strip-components=1 ffmpeg
          mv src-tauri/ffmpeg src-tauri/ffmpeg/ffmpeg-arm-unknown-linux-gnu
      - name: macarm
        run: |
          wget https://www.osxexperts.net/ffmpeg7arm.zip
          tar -xf ffmpeg7arm.zip -C src-tauri/ffmpeg --strip-components=1 ffmpeg
          mv src-tauri/ffmpeg src-tauri/ffmpeg/ffmpeg-x86_64-apple-darwin
      - run: chmod +x src-tauri/ffmpeg/*
      - run: ls -al src-tauri/ffmpeg
