name: test

on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            macos-latest/amd64,
            macos-latest/arm64,
            ubuntu-20.04/amd64,
            ubuntu-20.04/arm64,
            windows-latest/amd64,
            windows-latest/arm64
          ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: ubuntu-20.04/amd64
        if: matrix.platform == 'ubuntu-20.04/amd64'
        run: |
          mkdir -p src-tauri/ffmpeg
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          tar -xf ffmpeg-master-latest-linux64-gpl.tar.xz
          mv ffmpeg-master-latest-linux64-gpl/bin/ffmpeg src-tauri/ffmpeg/ffmpeg-x86_64-unknown-linux-gnu
      - name: ubuntu-20.04/arm64
        if: matrix.platform == 'ubuntu-20.04/arm64'
        run: |
          mkdir -p src-tauri/ffmpeg
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linuxarm64-gpl.tar.xz
          tar -xf ffmpeg-master-latest-linuxarm64-gpl.tar.xz
          mv ffmpeg-master-latest-linuxarm64-gpl/bin/ffmpeg src-tauri/ffmpeg/ffmpeg-arm-unknown-linux-gnu
      - name: windows-latest/amd64
        if: matrix.platform == 'windows-latest/amd64'
        run: |
          mkdir -p src-tauri/ffmpeg
          Invoke-WebRequest -Uri https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip -OutFile "ffmpeg-master-latest-win64-gpl.zip"
          unzip ffmpeg-master-latest-win64-gpl.zip
          mv ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe src-tauri/ffmpeg/ffmpeg-x86_64-windows-mvsc.exe
      - name: windows-latest/arm64
        if: matrix.platform == 'windows-latest/arm64'
        run: |
          mkdir -p src-tauri/ffmpeg
          Invoke-WebRequest -Uri https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-winarm64-gpl.zip -OutFile "ffmpeg-master-latest-winarm64-gpl.zip"
          unzip ffmpeg-master-latest-winarm64-gpl.zip
          mv ffmpeg-master-latest-winarm64-gpl/bin/ffmpeg.exe src-tauri/ffmpeg/ffmpeg-arm-windows-mvsc.exe
      - name: macos-latest/amd64
        if: matrix.platform == 'macos-latest/amd64'
        run: |
          mkdir -p src-tauri/ffmpeg
          wget https://www.osxexperts.net/ffmpeg7intel.zip
          unzip ffmpeg7intel.zip
          mv ffmpeg src-tauri/ffmpeg/ffmpeg-x86_64-apple-darwin
      - name: macos-latest/arm64
        if: matrix.platform == 'macos-latest/arm64'
        run: |
          mkdir -p src-tauri/ffmpeg
          wget https://www.osxexperts.net/ffmpeg7arm.zip
          unzip ffmpeg7arm.zip
          mv ffmpeg src-tauri/ffmpeg/ffmpeg-arm-unknown-linux-gnu
      - run: chmod +x src-tauri/ffmpeg/*
